config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :rides, except: [:edit, :update, :destroy]

  post '/places/selected', to: 'places#selected', as: :place_selected

  root to: 'rides#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/ride.rb
class Ride < ActiveRecord::Base
  belongs_to :departure_place, class_name: 'Place', foreign_key: 'departure_place_id'
  belongs_to :arrival_place, class_name: 'Place', foreign_key: 'arrival_place_id'

  validates :departure_place,
            :arrival_place,
            :price,
            :date,
            :contact_person_name,
            :contact_phone_number,
            :car_make_model,
            :car_seats,
            presence: true

  default_scope {order(:date)}
  scope :actual, -> {where(['date > ?', DateTime.now])}

  def self.permit_params
    [:departure_place_name,
     :arrival_place_name,
     :price,
     :date,
     :contact_person_name,
     :contact_phone_number,
     :car_make_model,
     :car_seats]
  end

  def departure_place_name=(name)
    self.departure_place = Place.find_or_create_by(name: name) unless name.blank?
  end

  def departure_place_name
    departure_place.name if departure_place
  end

  def arrival_place_name=(name)
    self.arrival_place = Place.find_or_create_by(name: name) unless name.blank?
  end

  def arrival_place_name
    arrival_place.name if arrival_place
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def selected
    respond_to do |format|
      place = Place.find_by_place_id params[:place][:place_id]
      place ||= Place.new(place_params)
      place.save if place.new_record?
      format.json {render json: 'ok'.to_json }
    end
  end

  private

    def place_params
      params[:place].permit(:name, :place_id, :vicinity, :lat, :lon)
    end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  def index
    @ride_search = Ride.actual.includes(:departure_place, :arrival_place).ransack(params[:q])
    @rides = @ride_search.result.page(params[:page]).per(10)
  end

  def show
    @ride = Ride.find(params[:id])
  end

  def new
    @ride = Ride.new
  end

  def create
    @ride = Ride.new(permit_params)
    if @ride.save
      redirect_to rides_path
    else
      render :new
    end
  end

  private

    def permit_params
      params.require(:ride).permit(Ride.permit_params)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-lg" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse"
              data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Вокзал', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to 'Предложить поездку', new_ride_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Вокзал" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Vokzal" %>">

    <link href='https://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic,700italic&subset=cyrillic-ext,latin,cyrillic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="wrap">
      <%= render 'layouts/navigation' %>
      <div class="container body">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
      <div id="push"></div>
    </div>

    <div id="footer">
      <div class="container">
        <p class="muted credit">
          &copy; <%= Time.zone.now.year %> Vokzal.KG
        </p>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/places/selected.html.erb
<h1>Places#selected</h1>
<p>Find me in app/views/places/selected.html.erb</p>

app/views/rides/_ride.html.erb
<%= link_to ride_path(ride), class: 'list-group-item' do %>
  <div class="row ride">
    <div class="col-sm-10">
      <h3>
        <span><%= ride.departure_place.vicinity %></span>
        <span>&#8594;</span>
        <span><%= ride.arrival_place.vicinity %></span>
      </h3>

      <div class="date">
        <span class="glyphicon glyphicon-time" style="color: #5da6de"></span>
        <%= ride.date.to_formatted_s(:short) %>
      </div>
    </div>

    <div class="col-sm-2">
      <h3>
        <%= number_to_currency ride.price, unit: 'Сом', format: '%n %u' %>
      </h3>

      <div>
        <%= ride.car_make_model %>
      </div>
    </div>

  </div>
<% end %>

app/views/rides/_search_form.html.erb
<div class="well">
  <%= search_form_for @ride_search, html: { class: 'form-inline rides-search-form' } do |f| %>

    <div class="form-group departure-place">
      <div class="input-group">
        <div class="input-group-addon">
          <span class="glyphicon glyphicon-map-marker"></span>
        </div>
        <%= f.search_field :departure_place_name_cont, placeholder: 'Место отправки', class: 'form-control' %>
      </div>
    </div>

    <div class="form-group arrival-place">
      <div class="input-group">
        <div class="input-group-addon"><span class="glyphicon glyphicon-map-marker"></span></div>
        <%= f.search_field :arrival_place_name_cont, placeholder: 'Место прибытия', class: 'form-control' %>
      </div>
    </div>

    <%= f.submit 'Filter', class: 'btn btn-primary' %>
  <% end %>

</div>

app/views/rides/index.html.erb
<%= render 'search_form' %>

<div class="list-group rides">
  <%= render @rides %>
  <%= paginate @rides %>
</div>

app/views/rides/new.html.erb
<div class="">
  <%= simple_form_for @ride, html: {class: 'form-horizontal'},
                      wrapper: :horizontal_form,
                      wrapper_mappings: {
                          check_boxes: :horizontal_radio_and_checkboxes,
                          radio_buttons: :horizontal_radio_and_checkboxes,
                          file: :horizontal_file_input,
                          boolean: :horizontal_boolean
                      } do |f| %>
    <%= f.input :departure_place_name %>
    <%= f.input :arrival_place_name %>
    <%= f.input :price %>
    <%= f.input :date, as: :datetime %>
    <%= f.input :contact_person_name %>
    <%= f.input :contact_phone_number %>
    <%= f.input :car_make_model %>
    <%= f.input :car_seats %>
    <%= f.button :submit, class: 'btn-primary' %>
  <% end %>
</div>

<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&language=ru&region=KG"></script>
<script>

  var options = {
    types: ['(cities)']
  };

  function handlePlaceInput(inputBoxId)
  {
    var inputPlaceAutoComplete = document.getElementById(inputBoxId);
    var autocomplete = new google.maps.places.Autocomplete(inputPlaceAutoComplete, options);

    google.maps.event.addListener(autocomplete, 'place_changed', function () {
      var place = {
        'place_id': autocomplete.getPlace().place_id,
        'vicinity': autocomplete.getPlace().vicinity,
        'name': $('#'+ inputBoxId).val(),
        'lat': autocomplete.getPlace().geometry.location.lat(),
        'lon': autocomplete.getPlace().geometry.location.lng()
      };
      console.log(place);
      $.post('<%= place_selected_path %>', {'place': place}, 'json');
    });
  }

  handlePlaceInput('ride_departure_place_name');
  handlePlaceInput('ride_arrival_place_name');

</script>

app/views/rides/show.html.erb
<div class="row ride-view">
  <div class="col-sm-10">

    <h1>
      <span><%= @ride.departure_place.name %></span>
      <span>&#8594;</span>
      <span><%= @ride.arrival_place.name %></span>,
      <span class="price"><%= number_to_currency @ride.price, unit: 'Сом', format: '%n %u' %></span>
    </h1>
    <dl class="dl-horizontal">
      <dt>Дата</dt>
      <dd><%= @ride.date.to_formatted_s(:short) %></dd>
      <dt>Авто</dt>
      <dd><%= @ride.car_make_model %></dd>
      <dt>Мест</dt>
      <dd><%= @ride.car_seats %></dd>
    </dl>
  </div>
  <div class="col-sm-2">
    <h1>
      <span class="glyphicon glyphicon-user"></span>
    </h1>
    <%= @ride.contact_person_name %>

    <div>
      <span class="glyphicon glyphicon-phone"></span>
      <%= @ride.contact_phone_number %>
    </div>

  </div>
</div>